[package]
name = "rita"
version = "0.3.14"
authors = ["Jehan <jehan.tremback@gmail.com>", "Ben <wangben3@gmail.com>"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "rita_exit"
path = "src/exit.rs"

[[bin]]
name = "rita"
path = "src/client.rs"

[dependencies]
althea_kernel_interface = { path = "../althea_kernel_interface" }
althea_types = { path = "../althea_types", features = ["actix"]}
babel_monitor = { path = "../babel_monitor" }
clu = { path = "../clu" }
exit_db = { path = "../exit_db" }
num256 = "0.2"
settings = { path = "../settings" }

guac_core = {git = "https://github.com/althea-mesh/guac_rs"}
web3 = {git = "https://github.com/althea-mesh/guac_rs"}
syslog = "4"
actix = "0.7"
actix-web = { version = "0.7", default_features = false, features= ["ssl"] }
actix_derive = "0.3"
bytes = "0.4"
config = "0.9"
diesel = { version = "1.3", features = ["postgres"] }
libsqlite3-sys = { version = "0.9", features = ["bundled"] }
docopt = "0.8"
dotenv = "0.13"
env_logger = "0.6"
failure = "0.1"
futures = "0.1"
handlebars = "1.1"
ipnetwork = "0.12.8"
lazy_static = "1.2"
log = "0.4"
minihttpse = "0.1"
mockito = "0.13"
mockstream = { git = "https://github.com/lazy-bitfield/rust-mockstream.git" }
rand = "0.5"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
regex = "1.1"
trust-dns-resolver = "0.10"
byteorder = { version = "1.2", features = ["i128"] }
openssl-probe = "0.1"
num-traits="0.2"
clarity = "0.1"
eui48 = "0.4"
arrayvec = {version= "0.4", features = ["serde-1"]}
lettre = {git="https://github.com/lettre/lettre.git"}
lettre_email = {git="https://github.com/lettre/lettre.git"}
phonenumber = "0.2"

[features]
default = []
development = []
system_alloc = []
